# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50f834d549b13135a5433db134f324599f28bf58aad8534f4f2bc7fb052e2704684c24b30958cfe86dd1bcc30814919224c8f3be3afe44e62d75da6e497cf984

test:
  secret_key_base: 93bf252d9f0b1decba6e18055d0e3d3ae7fcc73d2386f1b8efae42d69d6ef630fae2f6bf2cf80e72e28a833a34e11cd8a2c0d1cbf1337fdbc56f8974fcafd5a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
